package com.nuvio.tv.core.radar

import org.junit.Test
import org.junit.Assert.assertEquals

/** Reviewed metadata examples, not playback truth or independent accuracy labels. */
class SportsProviderEvidenceTest {
    @Test fun reviewed_provider_names_keep_their_evidence_boundaries() {
        assertEquals("production text case 1", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="India Cricket", away="West Indies Cricket", sport="Cricket", event="India Cricket vs West Indies Cricket", ts="2026-10-09T13:30:00"), listOf("cricket")), "(FLSP 596) | live:  West Indies vs India _ Cricket (West Indies vs India) (2026-10-09 09:30:00)").strength)
        assertEquals("production text case 2", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="India Cricket", away="West Indies Cricket", sport="Cricket", event="India Cricket vs West Indies Cricket", ts="2026-10-09T13:30:00"), listOf("cricket")), "(FLSP 273) | live:  West Indies vs India _ Cricket (West Indies vs India) (2026-10-09 09:30:00)").strength)
        assertEquals("production text case 3", 20, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="India Cricket", away="West Indies Cricket", sport="Cricket", event="India Cricket vs West Indies Cricket", ts="2026-10-09T13:30:00"), listOf("cricket")), "Carib SportsMax Cricket (S2) (D)").strength)
        assertEquals("production text case 4", 20, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="India Cricket", away="West Indies Cricket", sport="Cricket", event="India Cricket vs West Indies Cricket", ts="2026-10-09T13:30:00"), listOf("cricket")), "CRIC || TEN CRICKET").strength)
        assertEquals("production text case 5", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home=null, away=null, sport="Motorsport", event="Singapore Grand Prix Sprint Qualifying", ts="2026-10-09T12:30:00"), listOf("formula 1")), "CA (TSN+ 057) | Formula 1 Pit Lane _ Singapore Grand Prix Sprint Qualifying (2026-10-09 08:20:00)").strength)
        assertEquals("production text case 6", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home=null, away=null, sport="Motorsport", event="Singapore Grand Prix Sprint Qualifying", ts="2026-10-09T12:30:00"), listOf("formula 1")), "CA (TSN+ 058) | Formula 1 Mixed On_Board Camera _ Singapore Grand Prix Sprint Qualifying (2026-10-09 08:20:05)").strength)
        assertEquals("production text case 7", 0, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home=null, away=null, sport="Motorsport", event="Singapore Grand Prix Practice 1", ts="2026-10-09T08:30:00"), listOf("formula 1")), "SR: GRAND 1 ⱽᴵᴾ ᴿᴬᵂ").strength)
        assertEquals("production text case 8", 0, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Sydney FC", away="Western Sydney Wanderers", sport="Soccer", event="Sydney FC vs Western Sydney Wanderers", ts="2026-10-16T09:00:00"), listOf("Australian A-League")), "AU | A-League 04ⓧ: Western Sydney Wanderers v Sydney FC | Sat 19th Oct 9:35AM UK").strength)
        assertEquals("production text case 9", 0, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Macarthur FC", away="Perth Glory", sport="Soccer", event="Macarthur FC vs Perth Glory", ts="2026-10-17T06:00:00"), listOf("Australian A-League")), "AU | A-League 06ⓧ: Macarthur v Perth Glory | Sun 20th Oct 6:00AM UK").strength)
        assertEquals("production text case 10", 0, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Sydney FC", away="Western Sydney Wanderers", sport="Soccer", event="Sydney FC vs Western Sydney Wanderers", ts="2026-10-16T09:00:00"), listOf("Australian A-League")), "|AU| ABC Sydney HD").strength)
        assertEquals("production text case 11", 0, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Sydney FC", away="Western Sydney Wanderers", sport="Soccer", event="Sydney FC vs Western Sydney Wanderers", ts="2026-10-16T09:00:00"), listOf("Australian A-League")), "|AU| 7mate Sydney HD").strength)
        assertEquals("production text case 12", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Bragantino", away="Mirassol", sport="Soccer", event="Bragantino vs Mirassol", ts="2026-10-07T22:30:00"), listOf("Brazilian Serie A")), "(Fanatiz 016) | RB Bragantino vs Mirassol (2026-10-07 18:30:05)").strength)
        assertEquals("production text case 13", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Bragantino", away="Mirassol", sport="Soccer", event="Bragantino vs Mirassol", ts="2026-10-07T22:30:00"), listOf("Brazilian Serie A")), "(Fanatiz 003) | RB Bragantino vs Mirassol (2026-10-07 18:30:10)").strength)
        assertEquals("production text case 14", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Málaga", away="Espanyol", sport="Soccer", event="Málaga vs Espanyol", ts="2026-10-09T19:00:00"), listOf("Spanish La Liga")), "CA (TSN+ 064) | LaLiga: Malaga vs. Espanyol (2026-10-09 14:48:00)").strength)
        assertEquals("production text case 15", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Málaga", away="Espanyol", sport="Soccer", event="Málaga vs Espanyol", ts="2026-10-09T19:00:00"), listOf("Spanish La Liga")), "US (ESPN+ 279) | Spanish LALIGA: Malaga vs. Espanyol (Malaga vs. Espanyol) (2026-10-09 14:50:00)").strength)
        assertEquals("production text case 16", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Arsenal", away="Leeds United", sport="Soccer", event="Arsenal vs Leeds United", ts="2026-10-10T11:30:00"), listOf("English Premier League")), "AU (STAN 41) | Arsenal v Leeds United  Premier League Matchweek 6 2026/2027 (2026-10-10 21:30:29)").strength)
        assertEquals("production text case 17", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Arsenal", away="Leeds United", sport="Soccer", event="Arsenal vs Leeds United", ts="2026-10-10T11:30:00"), listOf("English Premier League")), "AU (STAN 42) |  • Arsenal v Leeds United  Premier League Matchweek 6 2026/2027 (2026-10-10 22:20:29)").strength)
        assertEquals("production text case 18", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Indiana Pacers", away="Minnesota Timberwolves", sport="Basketball", event="Indiana Pacers vs Minnesota Timberwolves", ts="2026-10-07T23:00:00"), listOf("NBA")), "(NBA 19) | Pacers vs Timberwolves (Pacers In_Arena) (2026-10-07 19:00:00)").strength)
        assertEquals("production text case 19", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Indiana Pacers", away="Minnesota Timberwolves", sport="Basketball", event="Indiana Pacers vs Minnesota Timberwolves", ts="2026-10-07T23:00:00"), listOf("NBA")), "NEXT | IND - PACERS VS MIN - TIMBERWOLVES | Wed 07 Oct 18:00 EDT (US) | 8K EXCLUSIVE | US: NBA PASS PPV 1").strength)
        assertEquals("production text case 20", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Dallas Cowboys", away="Tampa Bay Buccaneers", sport="American Football", event="Dallas Cowboys vs Tampa Bay Buccaneers", ts="2026-10-09T00:15:00"), listOf("NFL")), "US (ESPN+ 254) | Football: NFL Football: 2026 Week 5 Tampa Bay Buccaneers vs. Dallas Cowboys (NFL Football: 2026 Week 5 Tampa Bay Buccaneers vs. Dallas Cowboys) (2026-10-09 00:30:00)").strength)
        assertEquals("production text case 21", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Dallas Cowboys", away="Tampa Bay Buccaneers", sport="American Football", event="Dallas Cowboys vs Tampa Bay Buccaneers", ts="2026-10-09T00:15:00"), listOf("NFL")), "US (ESPN+ 259) | Football: NFL Football: Prime Vision 2026 Week 5 Tampa Bay Buccaneers vs. Dallas Cowboys (NFL Football: Prime Vision 2026 Week 5 Tampa Bay Buccaneers vs. Dallas Cowboys) (2026-10-09 05:00:00)").strength)
        assertEquals("production text case 22", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Washington Capitals", away="Pittsburgh Penguins", sport="Ice Hockey", event="Washington Capitals vs Pittsburgh Penguins", ts="2026-10-07T23:30:00"), listOf("nhl")), "US (MAX 055) | NHL on TNT: Penguins at Capitals (2026-10-07 19:00:00)").strength)
        assertEquals("production text case 23", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Washington Capitals", away="Pittsburgh Penguins", sport="Ice Hockey", event="Washington Capitals vs Pittsburgh Penguins", ts="2026-10-07T23:30:00"), listOf("nhl")), "NHL | 01 - 7:30pm Penguins at Capitals").strength)
        assertEquals("production text case 24", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Washington Capitals", away="Pittsburgh Penguins", sport="Ice Hockey", event="Washington Capitals vs Pittsburgh Penguins", ts="2026-10-07T23:30:00"), listOf("nhl")), "NEXT | NHL WASHINGTON - PITTSBURGH | Wed 07 Oct 19:35 EDT (US) | 8K EXCLUSIVE | US: VIAPLAY PPV 3").strength)
        assertEquals("production text case 25", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Washington Capitals", away="Pittsburgh Penguins", sport="Ice Hockey", event="Washington Capitals vs Pittsburgh Penguins", ts="2026-10-07T23:30:00"), listOf("nhl")), "NEXT | PITTSBURGH @ WASHINGTON | Wed 07 Oct 21:00 NDT (CA) | 8K EXCLUSIVE | CA: SPORTSNET PPV 9").strength)
        assertEquals("production text case 26", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home="Sydney Roosters", away="Newcastle Knights", sport="Rugby", event="Sydney Roosters vs Newcastle Knights", ts="2026-10-04T08:30:00"), listOf("Australian National Rugby League")), "CA (SN+ 001) | Grand Final _ Roosters vs. Knights (2026-10-04 04:00:00)").strength)
        assertEquals("production text case 27", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home=null, away=null, sport="Tennis", event="Japan Open Tennis Championships Vacherot vs Lehecka", ts="2026-10-05T00:00:00"), listOf("ATP World Tour")), "Tennis: Semifinale: J. Lehecka vs. V. Vacherot @ Oct 5 13:00 :Tv2Play NO  04").strength)
        assertEquals("production text case 28", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home=null, away=null, sport="Tennis", event="Japan Open Tennis Championships Alcaraz vs Munar", ts="2026-10-05T00:00:00"), listOf("ATP World Tour")), "Tennis: Semifinale: C. Alcaraz vs. J. Munar @ Oct 5 09:00 :Tv2Play NO  02").strength)
        assertEquals("production text case 29", 0, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home=null, away=null, sport="Tennis", event="Japan Open Tennis Championships Alcaraz vs Lehecka", ts="2026-10-06T00:00:00"), listOf("ATP World Tour")), "(MX) (Disney 016) | Carlos Alcaraz (ESP) vs. Valentin Vacherot (MON) (Semifinal) (2026-04-11 07:30:05)").strength)
        assertEquals("production text case 30", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home=null, away=null, sport="Fighting", event="UFC 333 Volkanovski vs Evloev", ts="2026-10-24T00:00:00"), listOf("ufc")), "US (UFC INT 21) | UFC 333: FIGHT PASS PRELIMS (2026-10-24 10:00:00)").strength)
        assertEquals("production text case 31", 60, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home=null, away=null, sport="Fighting", event="UFC 333 Volkanovski vs Evloev", ts="2026-10-24T00:00:00"), listOf("ufc")), "US (UFC INT 22) | UFC 333: FIGHT PASS PRELIMS (2026-10-24 10:00:05)").strength)
        assertEquals("production text case 32", 0, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home=null, away=null, sport="Fighting", event="UFC Fight Night 290 Allen vs Duncan", ts="2026-10-10T00:00:00"), listOf("ufc")), "PPV EVENT 14: The League Fight Night Tallinn (11.15 11:45AM ET)").strength)
        assertEquals("production text case 33", 0, SportsEventMatchEngine.name(SportsEventMatchEngine.prepare(RadarFixture(home=null, away=null, sport="Fighting", event="UFC Fight Night 290 Allen vs Duncan", ts="2026-10-10T00:00:00"), listOf("ufc")), "CA (TSN+ 025) | Monday Night Football with Peyton and Eli: Falcons vs. Saints (2026-10-05 20:15:00)").strength)
    }
}
