package com.nuvio.tv.core.iptv.identity

/**
 * B64 — the login-free identity of an M3U playlist and its items, identical on every platform.
 *
 * An M3U URL usually carries the provider login (`get.php?username=…&password=…`, `user:pass@host`,
 * or Xtream-style stream paths `/live/<user>/<pass>/<id>.ts`). Ids used to be derived from the raw
 * URL, so (a) a password change orphaned every favourite / Continue Watching / watched mark, and
 * (b) the login sat inside synced content ids (`xtream:m3u|http://…password=…:live:123`). Every id is
 * now derived from the URL with the login REMOVED (owner decision 2026-10-03):
 *
 *  - [loginFree] removes ONLY the login and leaves every other byte alone (no case / port / encoding
 *    normalisation), so a URL that never carried a login keeps its pre-B64 id — only login-bearing
 *    playlists and items re-key:
 *      - non-empty user-info (`user:pass@`) — an empty one (`udp://@239.0.0.1`) is not a login;
 *      - query parameters named (case-insensitively) `username user password pass passwd pwd`;
 *        a query that loses nothing stays byte-identical;
 *      - Xtream-style stream paths `/<live|movie|series|timeshift>/<a>/<b>/…` → `/<kind>/…` when
 *        `<a>/<b>` is the known login, or — login unknown — when the path is exactly
 *        `/<kind>/<a>/<b>/<digits>[.ext]` (a provider stream id: unambiguous, never a legit folder);
 *      - the short form `/<user>/<pass>/…` → `/…`, only when the login is known.
 *  - [playlistKey] = `m3u|` + [loginFree] of the (http-defaulted) URL, plus `|u` + hex8(FNV-1a(user))
 *    when a username was present, so two accounts on one panel stay two playlists without the
 *    username appearing in clear.
 *  - [itemSid] = Mobile's FNV-1a 31-bit hash ([sidOf]) of the login-free stream URL; the login is the
 *    playlist's ([loginOf] its URL), so a stream path that repeats it is cleaned exactly.
 *
 * Pure string work, no URL library and no platform Unicode API (FNV runs over UTF-16 code units):
 * twins are NuvioMobile/NuvioDesktop `features/iptv/identity/M3uIdentity.kt`, nuvio-web `src/lib/iptv/m3uIdentity.ts` and
 * the SQL port in nuvio-backend (`m3u_identity_*`); all pin the same golden vectors
 * (`M3uIdentityTest`), generated by research/b64-m3u-identity-ref.py.
 */
object M3uIdentity {

    /** The login carried by a playlist URL. Either part may be absent. */
    data class Login(val username: String?, val password: String?)

    private val CREDENTIAL_PARAMS = setOf("username", "user", "password", "pass", "passwd", "pwd")
    private val USERNAME_PARAMS = listOf("username", "user")
    private val PASSWORD_PARAMS = listOf("password", "pass", "passwd", "pwd")
    private val XTREAM_KINDS = setOf("live", "movie", "series", "timeshift")

    private class Parts(
        val prefix: String,      // "scheme://" or ""
        val userInfo: String?,   // non-empty user-info, already removed from authority
        val authority: String,
        val path: String,
        val query: String?,      // without '?'; null = no '?'
        val fragment: String,    // with '#', or ""
    )

    private fun split(url: String): Parts {
        val s = url.trim()
        val sep = s.indexOf("://")
        val prefix: String
        val rest: String
        if (sep > 0 && s.substring(0, sep).none { it == '/' || it == '?' || it == '#' }) {
            prefix = s.substring(0, sep + 3); rest = s.substring(sep + 3)
        } else {
            prefix = ""; rest = s
        }
        val authEnd = rest.indexOfFirst { it == '/' || it == '?' || it == '#' }.let { if (it < 0) rest.length else it }
        var authority = rest.substring(0, authEnd)
        var tail = rest.substring(authEnd)
        var userInfo: String? = null
        val at = authority.lastIndexOf('@')
        if (prefix.isNotEmpty() && at > 0) {
            userInfo = authority.substring(0, at)
            authority = authority.substring(at + 1)
        }
        val hash = tail.indexOf('#')
        val fragment = if (hash >= 0) tail.substring(hash) else ""
        if (hash >= 0) tail = tail.substring(0, hash)
        val q = tail.indexOf('?')
        val path = if (q >= 0) tail.substring(0, q) else tail
        val query = if (q >= 0) tail.substring(q + 1) else null
        return Parts(prefix, userInfo, authority, path, query, fragment)
    }

    private class Param(val name: String, val value: String, val raw: String)

    private fun params(query: String?): List<Param> =
        query?.split('&')?.map { kv ->
            val eq = kv.indexOf('=')
            Param(if (eq >= 0) kv.substring(0, eq) else kv, if (eq >= 0) kv.substring(eq + 1) else "", kv)
        } ?: emptyList()

    /** The login in [playlistUrl]: query parameters first (username/user, password/pass/passwd/pwd), else user-info. */
    fun loginOf(playlistUrl: String): Login? {
        val parts = split(playlistUrl)
        val ps = params(parts.query)
        fun first(names: List<String>): String? {
            for (n in names) ps.firstOrNull { it.name.lowercase() == n && it.value.isNotEmpty() }?.let { return it.value }
            return null
        }
        var user = first(USERNAME_PARAMS)
        var pass = first(PASSWORD_PARAMS)
        if (user == null && pass == null && parts.userInfo != null) {
            val info = parts.userInfo
            val colon = info.indexOf(':')
            user = (if (colon >= 0) info.substring(0, colon) else info).ifEmpty { null }
            pass = if (colon >= 0) info.substring(colon + 1).ifEmpty { null } else null
        }
        return if (user == null && pass == null) null else Login(user, pass)
    }

    private fun stripPathLogin(path: String, login: Login?): String {
        val segs = path.split('/')
        val user = login?.username
        val pass = login?.password
        val known = user != null && pass != null
        if (segs.size >= 5 && segs[0].isEmpty() && segs[1].lowercase() in XTREAM_KINDS) {
            val stem = segs.last().substringBefore('.')
            val streamIdShape = segs.size == 5 && stem.isNotEmpty() && stem.all { it in '0'..'9' }
            if ((known && segs[2] == user && segs[3] == pass) || streamIdShape) {
                return (segs.subList(0, 2) + segs.subList(4, segs.size)).joinToString("/")
            }
        }
        if (known && segs.size >= 4 && segs[0].isEmpty() && segs[1] == user && segs[2] == pass) {
            return (segs.subList(0, 1) + segs.subList(3, segs.size)).joinToString("/")
        }
        return path
    }

    /** [url] (trimmed) with the login removed and nothing else changed. [login] defaults to the URL's own. */
    fun loginFree(url: String, login: Login? = loginOf(url)): String {
        val parts = split(url)
        val path = stripPathLogin(parts.path, login)
        val query = parts.query?.let { q ->
            val ps = params(q)
            val kept = ps.filter { it.name.lowercase() !in CREDENTIAL_PARAMS }
            when {
                kept.size == ps.size -> "?$q"
                kept.isEmpty() -> ""
                else -> "?" + kept.joinToString("&") { it.raw }
            }
        } ?: ""
        return parts.prefix + parts.authority + path + query + parts.fragment
    }

    /** The permanent playlist key minted for a new M3U link playlist (null when [url] is blank). */
    fun playlistKey(url: String): String? {
        val raw = url.trim().takeIf { it.isNotEmpty() } ?: return null
        val full = withHttpScheme(raw)
        val login = loginOf(full)
        val discriminator = login?.username?.let { "|u" + hex8(it) } ?: ""
        return "m3u|" + loginFree(full, login) + discriminator
    }

    /** The id of a channel / movie (and, in hex, an episode) of a playlist whose login is [login]. */
    fun itemSid(streamUrl: String, login: Login?): Int = sidOf(loginFree(streamUrl, login))

    /** Episode ids stay strings (the registry EPISODE kind expects one) — hex of [itemSid]. */
    fun episodeId(streamUrl: String, login: Login?): String = itemSid(streamUrl, login).toString(16)

    /** FNV-1a 32 over UTF-16 code units, masked to a non-negative Int (Mobile's pre-B64 `sidOf`). */
    fun sidOf(s: String): Int = fnv32(s) and 0x7fffffff

    private fun fnv32(s: String): Int {
        var hash = -0x7ee3623b // 0x811C9DC5
        for (c in s) {
            hash = hash xor c.code
            hash *= 0x01000193
        }
        return hash
    }

    private fun hex8(s: String): String = fnv32(s).toUInt().toString(16).padStart(8, '0')

    private fun withHttpScheme(raw: String): String =
        if (raw.startsWith("http://", ignoreCase = true) || raw.startsWith("https://", ignoreCase = true)) raw
        else "http://$raw"
}
