package com.nuvio.tv.core.mediaserver

/**
 * Responses RECORDED from a real Jellyfin 12.2.0 whose library items are created on demand and whose streams are
 * prepared only when a title is opened or played. Pinned so the client keeps coping with that kind of server.
 */
internal object OnDemandServerFixtures {
    /** recorded OD_PLAYBACKINFO_FAST */
    const val OD_PLAYBACKINFO_FAST = """{"MediaSources":[{"Protocol":"File","Id":"e5ee43ab1c6f2d994dd43eb12b87795b","Path":"/stub","Type":"Default","Container":"mp4","Name":"Server A\n1080p\nWEB-DL H264 3.1 GB","IsRemote":false,"ETag":"687f4a4f7c77901200f1bdf51b53e584","RunTimeTicks":1200000000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":false,"SupportsDirectStream":true,"SupportsDirectPlay":true,"IsInfiniteStream":false,"UseMostCompatibleTranscodingProfile":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[{"Codec":"h264","CodecTag":"avc1","Language":"und","TimeBase":"1/12288","VideoRange":"SDR","VideoRangeType":"SDR","AudioSpatialFormat":"None","DisplayTitle":"360p H264 SDR","NalLengthSize":"4","IsInterlaced":false,"IsAVC":true,"BitRate":707365,"BitDepth":8,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"IsOriginal":false,"Height":360,"Width":640,"AverageFrameRate":24,"RealFrameRate":24,"ReferenceFrameRate":24,"Profile":"High","Type":"Video","AspectRatio":"16:9","Index":0,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"PixelFormat":"yuv420p","Level":30,"IsAnamorphic":false},{"Codec":"aac","CodecTag":"mp4a","Language":"und","TimeBase":"1/44100","VideoRange":"Unknown","VideoRangeType":"Unknown","AudioSpatialFormat":"None","LocalizedDefault":"Default","LocalizedExternal":"External","LocalizedLanguage":"Undetermined","LocalizedOriginal":"Original","DisplayTitle":"AAC - Mono - Default","IsInterlaced":false,"ChannelLayout":"mono","BitRate":69261,"Channels":1,"SampleRate":44100,"IsDefault":true,"IsForced":false,"IsHearingImpaired":false,"IsOriginal":false,"Profile":"LC","Type":"Audio","Index":1,"IsExternal":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false}],"MediaAttachments":[],"Formats":[],"Bitrate":782863,"RequiredHttpHeaders":{},"TranscodingSubProtocol":"http","DefaultAudioStreamIndex":1,"HasSegments":true}],"PlaySessionId":"dad48494540a4a0ba9d3b603990864e9"}"""

    /** recorded OD_PLAYBACKINFO_NO_STREAMS */
    const val OD_PLAYBACKINFO_NO_STREAMS = """{"MediaSources":[{"Protocol":"File","Id":"dd2cd0d310b47af5f74516c1ff88f43c","Path":"/stub","Type":"Default","IsRemote":false,"ETag":"dd2cd0d310b47af5f74516c1ff88f43c","RunTimeTicks":600000000,"ReadAtNativeFramerate":false,"IgnoreDts":false,"IgnoreIndex":false,"GenPtsInput":false,"SupportsTranscoding":false,"SupportsDirectStream":false,"SupportsDirectPlay":false,"IsInfiniteStream":false,"UseMostCompatibleTranscodingProfile":false,"RequiresOpening":false,"RequiresClosing":false,"RequiresLooping":false,"SupportsProbing":true,"VideoType":"VideoFile","MediaStreams":[],"MediaAttachments":[],"Formats":[],"RequiredHttpHeaders":{},"TranscodingSubProtocol":"http","HasSegments":true}],"PlaySessionId":"02c646e3acd74191b6fbac46427b9d4b"}"""

}
