package com.nuvio.tv.core.mediaserver

/**
 * Responses RECORDED (2026-10-06) from a standalone server that speaks the Jellyfin API and prepares each stream only
 * when a title is opened or played. We only TEST against recorded responses.
 */
internal object SlowResolveServerFixtures {
    const val SR_SYSTEM_INFO_PUBLIC = """{"Id":"0123456789abcdef0123456789abcdef","LocalAddress":"http://localhost:18108","ProductName":"Jellyfin Server","ServerName":"Home Server","StartupWizardCompleted":true,"Version":"10.11.8","OperatingSystem":""}"""

    const val SR_PLAYBACKINFO_FAST = """{"MediaSources":[{"Bitrate":145354,"Container":"mp4","DefaultAudioStreamIndex":1,"ETag":"56f044137ccf4d4a8da6cbd7a88311a5","GenPtsInput":false,"HasSegments":true,"Id":"56f044137ccf4d4a8da6cbd7a88311a5","IgnoreDts":false,"IgnoreIndex":false,"IsInfiniteStream":false,"IsRemote":false,"MediaStreams":[{"AudioSpatialFormat":"None","AverageFrameRate":10.0,"BitDepth":8,"BitRate":109382,"Codec":"h264","CodecTag":"avc1","DisplayTitle":"SD H264 Sdr 0.1 Mbps (Direct Play)","Height":270,"Index":0,"IsAvc":true,"IsDefault":true,"IsExternal":false,"IsForced":false,"IsHearingImpaired":false,"IsInterlaced":false,"IsTextSubtitleStream":false,"Language":"und","Level":21.0,"NalLengthSize":"4","Profile":"High","RealFrameRate":10.0,"RefFrames":1,"SupportsExternalStream":false,"TimeBase":"1/1000","Type":"Video","VideoRange":"SDR","VideoRangeType":"SDR","Width":480},{"AudioSpatialFormat":"None","BitRate":32564,"ChannelLayout":"mono","Channels":1,"Codec":"aac","DisplayTitle":"Mono - Default","Index":1,"IsAvc":false,"IsDefault":true,"IsExternal":false,"IsForced":false,"IsHearingImpaired":false,"IsInterlaced":false,"IsTextSubtitleStream":false,"Language":"und","LocalizedDefault":"Default","LocalizedExternal":"External","Profile":"LC","SampleRate":44100,"SupportsExternalStream":false,"TimeBase":"1/1000","Type":"Audio","VideoRange":"Unknown","VideoRangeType":"Unknown"}],"Name":"Server A\n1080p\nWEB-DL H264 3.1 GB","Path":"/media/d6e6378e-c2f7-5c58-a623-69831de1c090/file","Protocol":"File","ReadAtNativeFramerate":false,"RequiresClosing":false,"RequiresLooping":false,"RequiresOpening":false,"RunTimeTicks":9000000000,"Size":16352427,"SupportsDirectPlay":true,"SupportsDirectStream":true,"SupportsProbing":true,"SupportsTranscoding":true,"TranscodingSubProtocol":"http","Type":"Default","UseMostCompatibleTranscodingProfile":false,"VideoType":"VideoFile"}],"PlaySessionId":"dab27cd6d1ae4af8817b577efbf66cda"}"""

    const val SR_PLAYBACKINFO_NO_STREAMS = """{"MediaSources":[{"Bitrate":100,"Container":"mp4","ETag":"7b02fdd004074bab87bc7fb813defe58","Formats":[],"GenPtsInput":false,"HasSegments":false,"Id":"7b02fdd004074bab87bc7fb813defe58","IgnoreDts":false,"IgnoreIndex":false,"IsInfiniteStream":false,"IsRemote":false,"MediaStreams":[{"Codec":"h264","Height":360,"Index":0,"IsDefault":true,"IsExternal":false,"IsForced":false,"IsHearingImpaired":false,"IsInterlaced":false,"IsTextSubtitleStream":false,"SupportsExternalStream":false,"Type":"Video","Width":640}],"Name":"No streams found","Path":"/videos/no-streams","Protocol":"File","ReadAtNativeFramerate":false,"RequiredHttpHeaders":{},"RequiresClosing":false,"RequiresLooping":false,"RequiresOpening":false,"RunTimeTicks":360000000000,"Size":750710,"SupportsDirectPlay":true,"SupportsDirectStream":true,"SupportsProbing":true,"SupportsTranscoding":true,"TranscodingSubProtocol":"http","Type":"Default","UseMostCompatibleTranscodingProfile":false,"VideoType":"VideoFile"}],"PlaySessionId":"c72b3abe4c844eb8b5c1cda47606aa7c"}"""

    const val SR_PROBLEM_500 = """{"status":500,"title":"Internal Error","detail":"Something went wrong"}"""

    const val SR_PLAYBACKINFO_FORCE_TRANSCODE = """{"MediaSources":[{"Bitrate":145354,"Container":"mp4","DefaultAudioStreamIndex":1,"ETag":"56f044137ccf4d4a8da6cbd7a88311a5","Formats":[],"GenPtsInput":false,"HasSegments":true,"Id":"56f044137ccf4d4a8da6cbd7a88311a5","IgnoreDts":false,"IgnoreIndex":false,"IsInfiniteStream":false,"IsRemote":false,"MediaStreams":[{"AudioSpatialFormat":"None","AverageFrameRate":10.0,"BitDepth":8,"BitRate":109382,"Codec":"h264","CodecTag":"avc1","DisplayTitle":"SD H264 Sdr 0.1 Mbps (Direct Play)","Height":270,"Index":0,"IsAvc":true,"IsDefault":true,"IsExternal":false,"IsForced":false,"IsHearingImpaired":false,"IsInterlaced":false,"IsTextSubtitleStream":false,"Language":"und","Level":21.0,"NalLengthSize":"4","Profile":"High","RealFrameRate":10.0,"RefFrames":1,"SupportsExternalStream":false,"TimeBase":"1/1000","Type":"Video","VideoRange":"SDR","VideoRangeType":"SDR","Width":480},{"AudioSpatialFormat":"None","BitRate":32564,"ChannelLayout":"mono","Channels":1,"Codec":"aac","DisplayTitle":"Mono - Default","Index":1,"IsAvc":false,"IsDefault":true,"IsExternal":false,"IsForced":false,"IsHearingImpaired":false,"IsInterlaced":false,"IsTextSubtitleStream":false,"Language":"und","LocalizedDefault":"Default","LocalizedExternal":"External","Profile":"LC","SampleRate":44100,"SupportsExternalStream":false,"TimeBase":"1/1000","Type":"Audio","VideoRange":"Unknown","VideoRangeType":"Unknown"}],"Name":"Server A\n1080p\nWEB-DL H264 3.1 GB","Path":"/media/d6e6378e-c2f7-5c58-a623-69831de1c090/file","Protocol":"File","ReadAtNativeFramerate":false,"RequiredHttpHeaders":{},"RequiresClosing":false,"RequiresLooping":false,"RequiresOpening":false,"RunTimeTicks":9000000000,"Size":16352427,"SupportsDirectPlay":false,"SupportsDirectStream":false,"SupportsProbing":true,"SupportsTranscoding":true,"TranscodingContainer":"ts","TranscodingSubProtocol":"hls","TranscodingUrl":"/videos/56f04413-7ccf-4d4a-8da6-cbd7a88311a5/master.m3u8?PlaySessionId=49db5c9b8bea4f39aa22ab9f3d974241&MediaSourceId=d6e6378e-c2f7-5c58-a623-69831de1c090&VideoCodec=copy&AudioCodec=copy&AudioStreamIndex=1&ApiKey=a5ad8e41-e0a3-4cf8-8f87-23c8db2a8a2f","Type":"Default","UseMostCompatibleTranscodingProfile":false,"VideoType":"VideoFile"}],"PlaySessionId":"49db5c9b8bea4f39aa22ab9f3d974241"}"""

}
